# Generated by Django 3.1.4 on 2023-05-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230526_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
